import { AttarItem, Testimonial, FullCatalogAttar } from './types';

export const ATTARS: AttarItem[] = [
  {
    id: 'royal-musk',
    name: 'Royal Musk Rijali',
    tagline: 'The king of musks, a timeless classic',
    description: 'An majestic, thick, and white creamy musk that unfolds in opulent layers. Perfectly balanced with subtle warmth, this highly prestigious, non-alcoholic oil offers an unmatched aura of royalty and clean sophistication that lingers beautifully.',
    imagePath: '/images/royal_musk_rijali_1779296769471.png',
    notes: ['White Musk', 'Creamy Amber', 'Sandalwood', 'Sweet Powdery Accord'],
    longevity: '18+ Hours',
    projection: 'Heavy',
    category: 'Royal Musk',
    isPopular: true,
    price: 1899,
    intensity: 3,
    season: 'All-Season Elegance',
    topNotes: ['White Rose', 'Lily of the Valley'],
    heartNotes: ['Creamy Musk', 'Warm Amber Accord'],
    baseNotes: ['White Cedarwood', 'Sandalwood']
  },
  {
    id: 'cr7',
    name: 'CR-7',
    tagline: 'Bold and charismatic, for the modern connoisseur',
    description: 'A striking, sporty and sophisticated premium blend designed for the confident mind. Combining fresh metallic marine accords with a deeply rich undercurrent of dry woods, gold resins, and subtle spices. A fragrance of high ambition.',
    imagePath: '/images/cr7_perfume_1779296789402.png',
    notes: ['Marine Note', 'Tonka Bean', 'Cedarwood', 'Spicy Cardamom', 'Bergamot'],
    longevity: '12+ Hours',
    projection: 'Strong',
    category: 'Sleek Wood & Spice',
    price: 1499,
    intensity: 4,
    season: 'Summer & Active Wear',
    topNotes: ['Calabrian Bergamot', 'Ozone Accord', 'Grapefruit'],
    heartNotes: ['Spicy Cardamom', 'Marine Accord', 'Lavender'],
    baseNotes: ['Tonka Bean', 'Virginia Cedarwood', 'Patchouli']
  },
  {
    id: 'ruh-khus',
    name: 'Ruh Khus',
    tagline: "Earthy and cooling, nature's finest essence",
    description: 'Distilled using absolute traditional copper deg-bhapca methods from wild vetiver grass roots. Ruh Khus is a dark-green emerald of traditional perfumery. Saturated with an intense aroma of wet petrichor, cooling forest floor, and damp clay after heavy rain.',
    imagePath: '/images/ruh_khus_essence_1779296810684.png',
    notes: ['Wild Vetiver Root', 'Wet Soil', 'Damp Earth', 'Green Forest Pine'],
    longevity: '24+ Hours',
    projection: 'Intimate / Earthy',
    category: 'Pure Vetiver / Earthy',
    isPopular: true,
    price: 2199,
    intensity: 5,
    season: 'Monsoon Cooler & Relaxation',
    topNotes: ['Damp Soil Petrichor', 'Green Vetiver Grass'],
    heartNotes: ['Wild Vetiver Roots', 'Metallic Copper Pot Echo'],
    baseNotes: ['Rich Forest Vetivert', 'Warm Earth Patchouli']
  },
  {
    id: 'jannat-e-zuhr',
    name: 'Jannat-e-Zuhr',
    tagline: 'A heavenly blend of floral paradise',
    description: 'An ethereal fragrance that translates directly to "Heavenly Flower of midday". Blends incredibly smooth Jasmine Sambac, night-blooming blossoms, and sweet pristine honey with mild sacred frankincense, lifting spirits to higher realms.',
    imagePath: '/images/jannat_e_zuhr_1779296826760.png',
    notes: ['Jasmine Sambac', 'Nectar', 'Frankincense', 'White Rose', 'Sacred Herbs'],
    longevity: '14+ Hours',
    projection: 'Enveloping',
    category: 'Heavenly Floral / Incense',
    price: 1699,
    intensity: 3,
    season: 'Spring Morning Devotion',
    topNotes: ['Sweet Honeysuckle', 'Sacred Herbal Top'],
    heartNotes: ['Smooth Jasmine Sambac', 'Nectar', 'White Rose'],
    baseNotes: ['Frankincense Tears', 'Mild White Saffron']
  },
  {
    id: 'arba-wardath',
    name: 'Arba Wardath',
    tagline: 'Rich rose essence, the heart of luxury',
    description: 'Translating to "Four Roses", this is the ultimate romantic and majestic floral absolute. Crafted from prime handpicked Damask roses layered onto heavy red agarwood and amber, delivering a highly sensual, warm, and comforting luxury experience.',
    imagePath: '/images/arba_wardath_luxury_1779296847584.png',
    notes: ['Damask Rose', 'Red Amber', 'Agarwood (Oud)', 'Saffron', 'Musk'],
    longevity: '16+ Hours',
    projection: 'Extremely Strong',
    category: 'Royal Rose / Oud',
    price: 1799,
    intensity: 5,
    season: 'Winter Evening Cosiness',
    topNotes: ['Damask Rose Petals', 'Rich Saffron Threads'],
    heartNotes: ['Heavy Crimson Rose', 'Sweet Honey Nectar'],
    baseNotes: ['Cambodian Agarwood (Oud)', 'Warm Red Amber', 'Musk']
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Syed Abdul Rehman',
    location: 'Hyderabad, TS',
    rating: 5,
    text: 'A-ONE is my go-to for traditional attars. The Ruh Khus here is genuinely pure and matches the authentic copper-distilled vetiver profile of Kannauj. It lasts easily for two days on my cotton kurta.',
    date: 'April 2026'
  },
  {
    id: 't2',
    name: 'Venkatesh Prasad',
    location: 'Nalgonda, TS',
    rating: 5,
    text: 'The Royal Musk Rijali has got me so many compliments at family functions. It is extremely smooth, clean, and has none of that synthetic alcohol sting. Absolute luxury at a very honest price.',
    date: 'May 2026'
  },
  {
    id: 't3',
    name: 'Ibrahim Malik',
    location: 'Secunderabad',
    rating: 5,
    text: 'I ordered the Arba Wardath and CR-7. The CR-7 is fantastic for the office, while Arba Wardath is pure therapeutic bliss of real Damask rose. Looking forward to buying again!',
    date: 'March 2026'
  }
];

export const FULL_CATALOG_ATTARS: FullCatalogAttar[] = [
  { id: 'aurum-gold', sNo: 1, name: 'AURUM GOLD', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Special Collection' },
  { id: 'cr7-star', sNo: 2, name: 'CR-7 STAR', prices: { ml3: 80, ml6: 150, ml12: 300 }, category: 'Special Collection' },
  { id: 'bin-sheikh', sNo: 3, name: 'BIN SHEIKH', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Oud Collection' },
  { id: '1001-nights', sNo: 4, name: '1001 NIGHTS', prices: { ml3: 200, ml6: 400, ml12: 800 }, category: 'Special Collection' },
  { id: 'ruh-khus', sNo: 5, name: 'RUH KHUS', prices: { ml3: 300, ml6: 600, ml12: 1200 }, category: 'Oud Collection' },
  { id: 'oud-kuwaiti', sNo: 6, name: 'OUD KUWAITI', prices: { ml3: 200, ml6: 400, ml12: 800 }, category: 'Oud Collection' },
  { id: 'rashiqa', sNo: 7, name: 'RASHIQA', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Floral' },
  { id: 'bombay-oud', sNo: 8, name: 'BOMBAY OUD', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Oud Collection' },
  { id: 'classic-oud', sNo: 9, name: 'CLASSIC OUD', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Oud Collection' },
  { id: 'royal-misk-rijali', sNo: 10, name: 'ROYAL MISK RIJALI', prices: { ml3: 200, ml6: 400, ml12: 800 }, category: 'Musk Collection' },
  { id: 'amir-two', sNo: 11, name: 'AMIR TWO', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Oud Collection' },
  { id: 'al-haramain-madina', sNo: 12, name: 'AL HARAMAIN MADINA', prices: { ml3: 100, ml6: 200, ml12: 400 }, category: 'Floral' },
  { id: 'khamra-qahwa', sNo: 13, name: 'KHAMRA QAHWA', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Special Collection' },
  { id: 'misk-rijali-super', sNo: 14, name: 'MISK RIJALI SUPER', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Musk Collection' },
  { id: 'royal-woody', sNo: 15, name: 'ROYAL WOODY', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Special Collection' },
  { id: 'marj', sNo: 16, name: 'MARJ', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Special Collection' },
  { id: 'royal-galaxy', sNo: 17, name: 'ROYAL GALAXY', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Special Collection' },
  { id: 'jannat-e-zuhur', sNo: 18, name: 'JANNAT E ZUHUR', prices: { ml3: 200, ml6: 400, ml12: 800 }, category: 'Floral' },
  { id: 'white-mushk-spl', sNo: 19, name: 'WHITE MUSHK SPL', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Musk Collection' },
  { id: '9-pm-fruit', sNo: 20, name: '9 PM FRUIT', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Special Collection' },
  { id: 'dubai-rehan', sNo: 21, name: 'DUBAI REHAN', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Floral' },
  { id: 'shamamatul-amber', sNo: 22, name: 'SHAMAMATUL AMBER (B.R)', prices: { ml3: 180, ml6: 350, ml12: 700 }, category: 'Special Collection' },
  { id: 'baccarat-540', sNo: 23, name: 'BACCARAT 540', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Special Collection' },
  { id: 'jauf', sNo: 24, name: 'JAUF', prices: { ml3: 80, ml6: 150, ml12: 300 }, category: 'Special Collection' },
  { id: 'aqua', sNo: 25, name: 'AQUA', prices: { ml3: 80, ml6: 150, ml12: 300 }, category: 'Special Collection' },
  { id: 'mukhalat-arab', sNo: 26, name: 'MUKHALAT ARAB', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Oud Collection' },
  { id: 'arba-wardat', sNo: 27, name: 'ARBA WARDAT', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Floral' },
  { id: 'persian-oud', sNo: 28, name: 'PERSIAN OUD', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Oud Collection' },
  { id: 'mogra', sNo: 29, name: 'MOGRA', prices: { ml3: 80, ml6: 150, ml12: 300 }, category: 'Floral' },
  { id: 'silver', sNo: 30, name: 'SILVER', prices: { ml3: 50, ml6: 100, ml12: 200 }, category: 'Special Collection' },
  { id: 'kachi-kali', sNo: 31, name: 'KACHI KALI', prices: { ml3: 40, ml6: 80, ml12: 160 }, category: 'Floral' },
  { id: 'dareej', sNo: 32, name: 'DAREEJ (B.R)', prices: { ml3: 100, ml6: 200, ml12: 400 }, category: 'Special Collection' },
  { id: 'mukhallat-rashid', sNo: 33, name: 'MUKHALLAT RASHID (B.R)', prices: { ml3: 100, ml6: 200, ml12: 400 }, category: 'Oud Collection' },
  { id: 'arabian-nights', sNo: 34, name: 'ARABIAN NIGHTS', prices: { ml3: 130, ml6: 260, ml12: 550 }, category: 'Special Collection' },
  { id: 'oud-and-roses', sNo: 35, name: 'OUD & ROSES', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Oud Collection' },
  { id: 'mizyan', sNo: 36, name: 'MIZYAN', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Special Collection' },
  { id: 'ck-gold', sNo: 37, name: 'CK GOLD', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Special Collection' },
  { id: 'a-ones-oud', sNo: 38, name: 'A-ONE\'S OUD', prices: { ml3: 200, ml6: 400, ml12: 800 }, category: 'Oud Collection' },
  { id: 'lavender-oud', sNo: 39, name: 'LAVENDER OUD', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Oud Collection' },
  { id: 'hawas-ice', sNo: 40, name: 'HAWAS ICE', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Special Collection' },
  { id: 'musky-rose', sNo: 41, name: 'MUSKY ROSE', prices: { ml3: 130, ml6: 250, ml12: 500 }, category: 'Musk Collection' },
  { id: 'ajmeere', sNo: 42, name: 'AJMEERE (S.G)', prices: { ml3: 180, ml6: 350, ml12: 700 }, category: 'Special Collection' },
  { id: 'royal-aseel', sNo: 43, name: 'ROYAL ASEEL', prices: { ml3: 100, ml6: 200, ml12: 400 }, category: 'Special Collection' },
  { id: 'white-oud-super', sNo: 44, name: 'WHITE OUD SUPER', prices: { ml3: 150, ml6: 300, ml12: 600 }, category: 'Oud Collection' }
];

